### ISSUE TITLE
Feature Request: Add option to ignore certain files

### ISSUE THREAD

**Issue by lbsonley** [unic/gulp-data-validate#3]
Currently, every single file passed to this plugin with a `data.js` extension is validated against a schema file with the same name.

In order to allow for the definition of large configuration objects in separate `.data.js` files, we need a way to tell `gulp-data-validate` to ignore certain files. This is necessary for configuration objects with more than one top level property when each top level property would need a separate `$ref` in the target `schema.json` file.

## Example

Given a lengthy configuration that has been separated into a new file:

### separate-config.data.js

```
const config = {
  optionOne = {
    ...
  },
  optionTwo = {
    ...
  }
};

module.exports = config;
```

We would assume a schema file that looks like this:

### separate-config.schema.json

```
{
"$schema": "http://json-schema.org/draft-07/schema#",
"$comment": "",
"type": "object",
"additionalProperties": true,
"required": [],
"properties": {
  "optionOne": {
    ...
  },
  "optionTwo": {
    ...
  }
}
```

Then when we try to use `separate-config.schema.json` as a `$ref` in the main schema definition we would run into problems because each property needs a separate ref, which we don't have.
### main.schema.json
```
{
  ...
  
  "optionOne": {
    "$ref": "./separate-config.schema.json" <--- Does not work because this contains both Option 1 and Option 2 defs
  ...
}
```

## Proposed Solution

To remedy this, we could add an option `ignorePrefix` to the `gulp-data-validate` options. As a default, I would propose two underscores `__`. Why two? Becuase it is a common pattern to use one for handlebars partials that are never used on their own. This way, we will avoid conflicts between partials that begin with a single underscore but still have their own `data.js` and `schema.json` files that should be validated.

**Comment by lbsonley** [comment]
On second thought, the double underscore cause problems in Estatico. Using double underscores would require renaming handlebars partials to use double underscores as well, which is not something I want to do.

**Comment by robinloeffel** [comment]
> This way, we will avoid conflicts between partials that begin with a single underscore but still have their own data.js and schema.json files that should be validated.
Do we have cases where a file with a leading underscore requires a respective data file?

**Comment by lbsonley** [comment]
indeed we do. `atoms/button/partials/_button-content`

I guess as a solution, I could check for leading underscore after the check whether `schema.json` file exists.
https://github.com/unic/gulp-data-validate/blob/master/index.js#L23

**Comment by robinloeffel** [comment]
Yeah, that'd be cool. So that we could say that a regular file requires a data file, but one starting with an underscore does not.
